---
- name: Ensure required packages are installed
  ansible.builtin.apt:
    pkg: "{{ munin_node_packages }}"
    state: present
    cache_valid_time: 600

- name: Ensure config is latest
  ansible.builtin.template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    mode: "0644"
  notify: Restart munin-node

- name: Ensure plugin config is latest
  ansible.builtin.template:
    src: munin-node.j2
    dest: /etc/munin/plugin-conf.d/munin-node
    mode: "0644"
  notify: Restart munin-node

- name: Ensure extra plugins are present
  ansible.builtin.git:
    repo: https://github.com/munin-monitoring/contrib
    dest: /usr/local/share/munin-plugins
    update: "{{ munin_node_plugins_git_update }}"
    version: "{{ munin_node_plugins_git_version }}"
  when: munin_node_extra_plugins
  notify: Restart munin-node

- name: Ensure plugins are present
  ansible.builtin.file:
    src: "/usr/share/munin/plugins/{{ item }}"
    dest: "/etc/munin/plugins/{{ item }}"
    state: link
    force: yes
  with_items: "{{ munin_node_plugins_active }}"
  notify: Restart munin-node

- name: Ensure plugins are absent
  ansible.builtin.file:
    path: "/etc/munin/plugins/{{ item }}"
    state: absent
    force: yes
  with_items: "{{ munin_node_plugins_disabled }}"
  notify: Restart munin-node

- name: Ensure extra plugins are present
  ansible.builtin.file:
    src: "/usr/local/share/munin-plugins/plugins/{{ item.path }}"
    dest: "/etc/munin/plugins/{{ item.name }}"
  with_items: "{{ munin_node_extra_plugins_active }}"
  notify: Restart munin-node
