---
- name: ensure required packages are installed
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ munin_node_packages }}"

- name: ensure config is latest
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    mode: 0644
  notify: restart munin-node

- name: ensure plugin config is latest
  template:
    src: munin-node.j2
    dest: /etc/munin/plugin-conf.d/munin-node
    mode: 0644
  notify: restart munin-node

- name: ensure extra plugins are present
  git:
    repo: https://github.com/munin-monitoring/contrib
    dest: /usr/local/share/munin-plugins
    update: "{{ munin_node_plugins_git_update }}"
  when: munin_node_extra_plugins
  notify: restart munin-node

- name: ensure plugins are present
  file:
    src: "/usr/share/munin/plugins/{{ item }}"
    dest: "/etc/munin/plugins/{{ item }}"
    state: link
    force: yes
  with_items: "{{ munin_node_plugins_active }}"
  notify: restart munin-node

- name: ensure plugins are absent
  file:
    path: "/etc/munin/plugins/{{ item }}"
    state: absent
    force: yes
  with_items: "{{ munin_node_plugins_disabled }}"
  notify: restart munin-node

- name: ensure extra plugins are present
  file:
    src: "/usr/local/share/munin-plugins/plugins/{{ item.path }}"
    dest: "/etc/munin/plugins/{{ item.name }}"
  with_items: "{{ munin_node_extra_plugins_active }}"
  notify: restart munin-node
